### ISSUE TITLE
Community Guidlines

### ISSUE THREAD

**Issue by rabernat** [ihesp/IPART#6]
This issue is in reference to my JOSS review (https://github.com/openjournals/joss-reviews/issues/2407)

> Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I didn't find this information in your docs. However, it does appear to be in your README.

> If you encounter problems or would like to help improve the code, please don't hesitate to fire up an issue or pull request.

This is a pretty terse contributor guide. You may wish to elaborate it a bit.

**Comment by Xunius** [comment]
Please checkout [this commit](https://github.com/ihesp/IPART/commit/def1379d471d51bb9faa567fa40018f1f58fed8b), I copied from https://github.com/neurohackademy/nh2020-curriculum/blob/master/tu-python-libraries-rokem/03-setup-file.md

**Comment by Xunius** [comment]
@kbarnhart What further changes need to be done regarding this issue?

**Comment by kbarnhart** [comment]
@Xunius it looks to me like this has been addressed. I don't believe I have privileges to close the issue, but it looks like it can be closed.

**Comment by rabernat** [comment]
Great, this is definitely a big improvement. I just have one recommendation. When you reference the project's GitHub page and issue tracker in the docs, provide a hyperlink so it's easier for users to find them.

> I copied from https://github.com/neurohackademy/nh2020-curriculum/blob/master/tu-python-libraries-rokem/03-setup-file.md

If you are copying directly from another package, you will need to provide proper attribution. Unfortunately the licensing on the neurohackacademy repo is not clear (see https://github.com/neurohackademy/nh2020-curriculum/issues/42).

**Comment by kbarnhart** [comment]
@Xunius it looks like @rabernat's issue (neurohackademy/nh2020-curriculum#42) has clarified the license on the neurohackacademy. Once you have provided appropriate attribution for the contribution guidelines I think this issue can be closed.

**Comment by Xunius** [comment]
@rabernat @kbarnhart. Hi all, I've just added attribution to neurohackacademy in [this commit](https://github.com/ihesp/IPART/commit/ad7fd5708edf799084ef44f5abdfbad93ba25850).
